Hey there, you're probably here because your migrations aren't running correctly. Before you puch this computer try this command if you've already created changes in your models

alembic revision --autogenerate -m "Put revision message here"

THEN...
DON'T FORGET the command...

alembic upgrade head


10a46ab1510e_added_api_key_to_user_model.py

"""Added api key to User model

Revision ID: 10a46ab1510e
Revises: e33acf704ad1
Create Date: 2023-06-05 20:47:14.401313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a46ab1510e'
down_revision = 'e33acf704ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    op.create_unique_constraint(True, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(True, 'users', type_='unique')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
